'use client';

import { useEffect, useMemo, useState } from 'react';
import { citizenVerifyResolution, createComplaint, findDuplicateComplaints, nearbyProjects, transitionComplaint, uploadEvidence } from '@/src/lib/civic-supabase';
import { login, logout, register } from '@/src/lib/auth';
import { createSupabaseBrowserClient } from '@/src/lib/supabase';
import type { Category, Complaint, Profile, Project } from '@/src/lib/types';

const statuses = ['SUBMITTED','VERIFIED','ASSIGNED','IN_PROGRESS','CITIZEN_VERIFICATION','RESOLVED','CLOSED','REOPENED','ESCALATED','ON_HOLD','REJECTED'];
type Tab = 'overview'|'report'|'complaints'|'officer'|'admin'|'projects';
const msg = (e: unknown) => e instanceof Error ? e.message : 'Something went wrong';
const shortId = (id: string) => id.slice(0,8).toUpperCase();

export default function Phase3Page() {
  const supabase = useMemo(() => createSupabaseBrowserClient(), []);
  const [profile,setProfile]=useState<Profile|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState('');
  const [categories,setCategories]=useState<Category[]>([]),[complaints,setComplaints]=useState<Complaint[]>([]),[projects,setProjects]=useState<Project[]>([]),[notifications,setNotifications]=useState<any[]>([]),[officers,setOfficers]=useState<Profile[]>([]);
  const [tab,setTab]=useState<Tab>('overview'),[selected,setSelected]=useState<Complaint|null>(null),[history,setHistory]=useState<any[]>([]),[evidence,setEvidence]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[filter,setFilter]=useState('ALL');
  const [form,setForm]=useState({categoryId:'',description:'',latitude:'',longitude:'',address:'',severity:'MEDIUM',projectId:''});
  const isOfficer=['Officer','Department Admin','Super Admin'].includes(profile?.role ?? ''), isAdmin=['Department Admin','Super Admin'].includes(profile?.role ?? '');
  const visible=filter==='ALL'?complaints:complaints.filter(c=>c.status===filter), open=complaints.filter(c=>!['CLOSED','REJECTED'].includes(c.status)).length, resolved=complaints.filter(c=>['RESOLVED','CLOSED'].includes(c.status)).length, critical=complaints.filter(c=>c.severity==='CRITICAL'&&!['CLOSED','REJECTED'].includes(c.status)).length;

  async function refresh(){
    const {data:auth}=await supabase.auth.getUser(); let p:Profile|null=null;
    if(auth.user){const {data}=await supabase.from('profiles').select('*').eq('id',auth.user.id).maybeSingle();p=(data as Profile|null)??null;} setProfile(p);
    const [{data:cats},{data:cs},{data:ps}]=await Promise.all([supabase.from('categories').select('*').eq('is_active',true).order('name'),supabase.from('complaints').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('projects').select('*').order('name').limit(100)]);
    setCategories((cats??[]) as Category[]);setComplaints((cs??[]) as Complaint[]);setProjects((ps??[]) as Project[]);
    if(auth.user){const {data:n}=await supabase.from('notifications').select('*').eq('user_id',auth.user.id).order('created_at',{ascending:false}).limit(20);setNotifications(n??[]);if(isOfficer){const {data:o}=await supabase.from('profiles').select('*').in('role',['Officer','Department Admin','Super Admin']).order('full_name');setOfficers((o??[]) as Profile[]);}} else {setNotifications([]);setOfficers([]);}
  }
  useEffect(()=>{refresh().catch(e=>setMessage(`Error: ${msg(e)}`));},[]);

  async function locate(){if(!navigator.geolocation)return setMessage('Location is not supported by this browser.');navigator.geolocation.getCurrentPosition(p=>setForm(f=>({...f,latitude:p.coords.latitude.toFixed(6),longitude:p.coords.longitude.toFixed(6)})),e=>setMessage(`Location error: ${e.message}`),{enableHighAccuracy:true,timeout:10000});}
  async function submit(){if(!profile)return setMessage('Please login before submitting a complaint.');setBusy(true);try{const latitude=Number(form.latitude),longitude=Number(form.longitude);const d=await findDuplicateComplaints({categoryId:form.categoryId,latitude,longitude});if(d.length){setMessage(`⚠️ ${d.length} similar report(s) found nearby. Review existing reports before creating another.`);setTab('complaints');return;}const near=await nearbyProjects(latitude,longitude);const id=await createComplaint({...form,latitude,longitude,projectId:form.projectId||near[0]?.id});setMessage(`Complaint #${shortId(id)} submitted successfully.`);setForm({categoryId:'',description:'',latitude:'',longitude:'',address:'',severity:'MEDIUM',projectId:''});await refresh();setTab('complaints');}catch(e){setMessage(`Error: ${msg(e)}`);}finally{setBusy(false);}}
  async function selectComplaint(c:Complaint){setSelected(c);const [{data:h},{data:ev}]=await Promise.all([supabase.from('complaint_status_history').select('*').eq('complaint_id',c.id).order('created_at',{ascending:true}),supabase.from('evidence').select('*').eq('complaint_id',c.id).order('created_at',{ascending:false})]);setHistory(h??[]);setEvidence(ev??[]);}
  async function action(fn:()=>Promise<unknown>,success:string){setBusy(true);try{await fn();setMessage(success);await refresh();if(selected)await selectComplaint(selected);}catch(e){setMessage(`Error: ${msg(e)}`);}finally{setBusy(false);}}
  async function upload(){if(!selected||!file)return;await action(()=>uploadEvidence({file,complaintId:selected.id,evidenceType:file.type.startsWith('image/')?'PHOTO':'DOCUMENT'}),'Evidence uploaded.');setFile(null);}

  return <main>
    <header className="hero"><div><span className="badge">PHASE 3 • CIVIC INTELLIGENCE</span><h1>CivicBrain <span>360</span></h1><p>Report. Track. Resolve. Make every civic issue visible.</p></div><div className="auth-box">{profile?<><strong>{profile.full_name||'Citizen'}</strong><small>{profile.role}</small><button className="secondary" onClick={()=>logout().then(refresh).then(()=>setMessage('Logged out.'))}>Logout</button></>:<button onClick={()=>document.getElementById('auth')?.scrollIntoView({behavior:'smooth'})}>Login / Register</button>}</div></header>
    <nav className="tabs">{(['overview','report','complaints','officer','admin','projects'] as Tab[]).map(t=>(t==='officer'&&!isOfficer)||(t==='admin'&&!isAdmin)?null:<button key={t} className={tab===t?'active':'secondary'} onClick={()=>setTab(t)}>{t==='overview'?'Overview':t==='report'?'Report Issue':t==='complaints'?'My Complaints':t==='officer'?'Officer Desk':t==='admin'?'Admin':'Projects'}</button>)}</nav>
    {message&&<div className={message.startsWith('Error')?'alert error':'alert success'}>{message}<button className="close" onClick={()=>setMessage('')}>×</button></div>}
    {tab==='overview'&&<><section className="stats grid4"><Stat label="Total Reports" value={complaints.length} icon="📋"/><Stat label="Open Issues" value={open} icon="🔎"/><Stat label="Resolved" value={resolved} icon="✅"/><Stat label="Critical Open" value={critical} icon="🚨"/></section><div className="grid2"><section className="card feature"><span className="eyebrow">CITIZEN POWER</span><h2>One report can move a whole community.</h2><p>Detect duplicates, link issues to projects, preserve the full status history, and let citizens verify the final resolution.</p><button onClick={()=>setTab('report')}>Report a Civic Issue →</button></section><section className="card"><h2>Recent activity</h2>{complaints.slice(0,6).map(c=><button className="list-row" key={c.id} onClick={()=>{selectComplaint(c);setTab('complaints')}}><span><b>#{shortId(c.id)}</b> {c.description}</span><Status status={c.status}/></button>)}{!complaints.length&&<Empty text="No complaints yet."/>}</section></div><section id="auth" className="card"><h2>Account access</h2><div className="grid3"><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="For registration"/></label></div><nav><button onClick={()=>login(email,password).then(refresh).then(()=>setMessage('Welcome back!')).catch(e=>setMessage(`Error: ${msg(e)}`))}>Login</button><button className="secondary" onClick={()=>register(email,password,name).then(refresh).then(()=>setMessage('Registered. Check email if confirmation is enabled.')).catch(e=>setMessage(`Error: ${msg(e)}`))}>Create Citizen Account</button></nav></section></>}
    {tab==='report'&&<section className="card"><div className="section-title"><div><span className="eyebrow">NEW REPORT</span><h2>Tell us what is happening</h2></div><button className="secondary" onClick={locate}>📍 Use my location</button></div><div className="grid2"><label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Choose a category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(s=><option key={s}>{s}</option>)}</select></label><label className="wide">Description<textarea rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe the issue, landmarks and impact."/></label><label>Latitude<input value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})} placeholder="12.9716"/></label><label>Longitude<input value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})} placeholder="77.5946"/></label><label className="wide">Address / landmark<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="wide">Related project<select value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value})}><option value="">Auto-detect nearby project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><button disabled={busy} onClick={submit}>{busy?'Submitting...':'Check duplicates & submit report'}</button><p className="hint">Reports are stored with location, audit history, project links and notifications.</p></section>}
    {tab==='complaints'&&<div className="grid2"><section className="card"><div className="section-title"><h2>{profile?'Your complaints':'Complaint explorer'}</h2><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>{visible.filter(c=>!profile||c.created_by===profile.id).map(c=><button className={`complaint-row ${selected?.id===c.id?'selected':''}`} key={c.id} onClick={()=>selectComplaint(c)}><div><strong>#{shortId(c.id)}</strong><p>{c.description}</p><small>{new Date(c.created_at).toLocaleString()} · {c.severity}</small></div><Status status={c.status}/></button>)}{!visible.filter(c=>!profile||c.created_by===profile.id).length&&<Empty text={profile?'No complaints match this filter.':'Login to see your complaints.'}/>}</section><Detail complaint={selected} profile={profile} history={history} evidence={evidence} file={file} setFile={setFile} upload={upload} action={action}/></div>}
    {tab==='officer'&&isOfficer&&<section className="card"><div className="section-title"><div><span className="eyebrow">OPERATIONS</span><h2>Officer desk</h2></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ALL</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Issue</th><th>Status</th><th>Severity</th><th>Assign</th><th>Actions</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><b>#{shortId(c.id)}</b><br/>{c.description}</td><td><Status status={c.status}/></td><td>{c.severity}</td><td><select value={c.assigned_to??''} onChange={e=>action(()=>transitionComplaint(c.id,'ASSIGNED','Assigned from officer desk',e.target.value||undefined),'Complaint assigned.') }><option value="">Unassigned</option>{officers.map(o=><option key={o.id} value={o.id}>{o.full_name||o.id.slice(0,6)}</option>)}</select></td><td><nav className="mini">{c.status==='SUBMITTED'&&<button onClick={()=>action(()=>transitionComplaint(c.id,'VERIFIED','Officer verified'),'Verified.')}>Verify</button>}{['VERIFIED','ASSIGNED','REOPENED'].includes(c.status)&&<button onClick={()=>action(()=>transitionComplaint(c.id,'IN_PROGRESS','Work started'),'Work started.')}>Start</button>}{c.status==='IN_PROGRESS'&&<button onClick={()=>action(()=>transitionComplaint(c.id,'CITIZEN_VERIFICATION','Resolution submitted'),'Resolution sent to citizen.')}>Submit resolution</button>}</nav></td></tr>)}</tbody></table></div></section>}
    {tab==='admin'&&isAdmin&&<section className="grid2"><section className="card"><span className="eyebrow">ADMIN OVERVIEW</span><h2>System health</h2><div className="admin-metrics"><Stat label="Unique reporters" value={new Set(complaints.map(c=>c.created_by)).size} icon="👥"/><Stat label="Projects" value={projects.length} icon="🏗️"/><Stat label="Departments" value={new Set(projects.map(p=>p.department_id).filter(Boolean)).size} icon="🏢"/><Stat label="Resolution rate" value={`${complaints.length?Math.round(resolved/complaints.length*100):0}%`} icon="📈"/></div></section><section className="card"><h2>Severity watch</h2>{['CRITICAL','HIGH','MEDIUM','LOW'].map(s=><div className="bar-row" key={s}><b>{s}</b><div className="bar"><i style={{width:`${complaints.length?Math.round(complaints.filter(c=>c.severity===s).length/complaints.length*100):0}%`}}/></div><span>{complaints.filter(c=>c.severity===s).length}</span></div>)}</section><section className="card wide"><h2>Status distribution</h2><div className="status-grid">{statuses.map(s=><div key={s}><b>{complaints.filter(c=>c.status===s).length}</b><span>{s.replaceAll('_',' ')}</span></div>)}</div></section></section>}
    {tab==='projects'&&<section className="card"><div className="section-title"><div><span className="eyebrow">PUBLIC INTELLIGENCE</span><h2>Project explorer</h2></div><span className="badge">{projects.length} projects</span></div><div className="project-grid">{projects.map(p=><article className="project" key={p.id}><span className="project-icon">🏗️</span><h3>{p.name}</h3><Status status={p.status}/><p>{p.description||'No description provided.'}</p><small>{p.panchayat||'Location not specified'} · {p.latitude??'—'}, {p.longitude??'—'}</small><div className="project-footer">{complaints.filter(c=>c.project_id===p.id).length} linked reports</div></article>)}{!projects.length&&<Empty text="No projects available."/>}</div></section>}
    {notifications.length>0&&<aside className="notifications"><b>🔔 Notifications</b>{notifications.slice(0,4).map(n=><button key={n.id} onClick={()=>supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',n.id).then(refresh)} className={n.read_at?'read':''}><strong>{n.title}</strong><span>{n.body}</span></button>)}</aside>}
  </main>;
}
function Stat({label,value,icon}:{label:string;value:string|number;icon:string}){return <div className="stat"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></div>}
function Status({status}:{status:string}){return <span className={`status s-${status.toLowerCase()}`}>{status.replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Detail({complaint,profile,history,evidence,file,setFile,upload,action}:{complaint:Complaint|null;profile:Profile|null;history:any[];evidence:any[];file:File|null;setFile:(f:File|null)=>void;upload:()=>Promise<void>;action:(fn:()=>Promise<unknown>,success:string)=>Promise<void>}){
  if(!complaint)return <section className="card detail empty">Select a complaint to view its timeline, evidence and actions.</section>;
  const canVerify=profile?.id===complaint.created_by&&complaint.status==='CITIZEN_VERIFICATION';
  return <section className="card detail"><div className="section-title"><div><span className="eyebrow">COMPLAINT #{shortId(complaint.id)}</span><h2>{complaint.description}</h2></div><Status status={complaint.status}/></div><div className="detail-grid"><div><small>Severity</small><b>{complaint.severity}</b></div><div><small>Address</small><b>{complaint.address||'Not provided'}</b></div><div><small>Coordinates</small><b>{complaint.latitude}, {complaint.longitude}</b></div><div><small>Created</small><b>{new Date(complaint.created_at).toLocaleString()}</b></div></div><h3>Status timeline</h3><div className="timeline">{history.map(h=><div key={h.id}><span/><div><b>{h.to_status.replaceAll('_',' ')}</b><small>{h.reason||'Status updated'} · {new Date(h.created_at).toLocaleString()}</small></div></div>)}</div>{canVerify&&<div className="verify"><b>Was this issue actually resolved?</b><nav><button onClick={()=>action(()=>citizenVerifyResolution(complaint.id,true),'Complaint closed. Thanks for verifying.')}>Yes, resolved</button><button className="secondary" onClick={()=>action(()=>citizenVerifyResolution(complaint.id,false,'Issue still exists'),'Complaint reopened.')}>No, reopen</button></nav></div>}<h3>Evidence</h3><div className="evidence">{evidence.map(e=><a key={e.id} href={e.file_url||'#'} target="_blank" rel="noreferrer">📎 {e.evidence_type} · {new Date(e.created_at).toLocaleDateString()}</a>)}{!evidence.length&&<small>No evidence uploaded yet.</small>}</div>{profile&&<div className="upload"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,video/mp4" onChange={e=>setFile(e.target.files?.[0]??null)}/><button disabled={!file} onClick={upload}>Upload evidence</button></div>}</section>
}
